@ECHO OFF
FOR /F "tokens=* USEBACKQ" %%F IN (`git describe --dirty --always --abbrev=0`) DO (
	SET git_short_version=%%F
)
if "%git_short_version%"=="%%F" SET git_short_version=UNKNOWN

SET header=src\version.h.gen

ECHO /* Generated by generate_version.sh--do not edit! */ > %header%
ECHO #ifndef VERSION_H >> %header%
ECHO #define VERSION_H >> %header%
ECHO #define GIT_SHORT_VERSION ("%git_short_version%") >> %header%
ECHO #define COPYRIGHT ("Copyright (c) 2018 The KnightOS Group\n") >> %header%
ECHO #define LICENSE ("License MIT/X11\n") >> %header%
ECHO #endif >> %header%

